controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_connexionadmin:
    path: /connexionadmin
    controller: App\Controller\AdminconnexionController::index

app_login_check:
    path: /connexionadmin/check
